### ISSUE TITLE
"[Command] 'OutputVerbosity' invoked" every 500ms

### ISSUE THREAD

**Issue by RichardD2** [madskristensen/EventLogVS#1]
**Describe the bug**
The output window logs `[Command] 'OutputVerbosity' invoked` twice a second, even though no such command is invoked.

**To Reproduce**
Open the output window. 
Select "Event Timeline". 
Watch the window fill up with:

```
14:13:31	[Command] 'OutputVerbosity' invoked
14:13:31	[Command] 'OutputVerbosity' invoked
14:13:32	[Command] 'OutputVerbosity' invoked
14:13:32	[Command] 'OutputVerbosity' invoked
14:13:33	[Command] 'OutputVerbosity' invoked
14:13:33	[Command] 'OutputVerbosity' invoked
14:13:34	[Command] 'OutputVerbosity' invoked
14:13:34	[Command] 'OutputVerbosity' invoked
14:13:35	[Command] 'OutputVerbosity' invoked
14:13:35	[Command] 'OutputVerbosity' invoked
14:13:36	[Command] 'OutputVerbosity' invoked
14:13:36	[Command] 'OutputVerbosity' invoked
14:13:37	[Command] 'OutputVerbosity' invoked
14:13:37	[Command] 'OutputVerbosity' invoked
14:13:38	[Command] 'OutputVerbosity' invoked
14:13:38	[Command] 'OutputVerbosity' invoked
14:13:39	[Command] 'OutputVerbosity' invoked
14:13:39	[Command] 'OutputVerbosity' invoked
14:13:40	[Command] 'OutputVerbosity' invoked
14:13:41	[Command] 'OutputVerbosity' invoked
14:13:41	[Command] 'OutputVerbosity' invoked
14:13:42	[Command] 'OutputVerbosity' invoked
14:13:42	[Command] 'OutputVerbosity' invoked
14:13:43	[Command] 'OutputVerbosity' invoked
14:13:43	[Command] 'OutputVerbosity' invoked
14:13:44	[Command] 'OutputVerbosity' invoked
14:13:44	[Command] 'OutputVerbosity' invoked
14:13:45	[Command] 'OutputVerbosity' invoked
14:13:45	[Command] 'OutputVerbosity' invoked
14:13:46	[Command] 'OutputVerbosity' invoked
14:13:46	[Command] 'OutputVerbosity' invoked
14:13:47	[Command] 'OutputVerbosity' invoked
14:13:47	[Command] 'OutputVerbosity' invoked
14:13:48	[Command] 'OutputVerbosity' invoked
14:13:48	[Command] 'OutputVerbosity' invoked
14:13:49	[Command] 'OutputVerbosity' invoked
14:13:49	[Command] 'OutputVerbosity' invoked
14:13:50	[Command] 'OutputVerbosity' invoked
14:13:50	[Command] 'OutputVerbosity' invoked
14:13:51	[Command] 'OutputVerbosity' invoked
14:13:51	[Command] 'OutputVerbosity' invoked
14:13:52	[Command] 'OutputVerbosity' invoked
14:13:52	[Command] 'OutputVerbosity' invoked
14:13:53	[Command] 'OutputVerbosity' invoked
14:13:53	[Command] 'OutputVerbosity' invoked
...
```

**Additional details:**
Event Timeline v1.0.10

Microsoft Visual Studio Professional 2022 Version 17.6.4
VisualStudio.17.Release/17.6.4+33815.320
Microsoft .NET Framework Version 4.8.09032

ADL Tools Service Provider   1.0
ASA Service Provider   1.0
ASP.NET and Web Tools   17.6.326.62524
ASP.NET Web Frameworks and Tools 2012   17.6.326.62524
Azure App Service Tools v3.0.0   17.6.326.62524
Azure Data Lake Tools for Visual Studio   2.6.5000.0
Azure Functions and Web Jobs Tools   17.6.326.62524
Azure Stream Analytics Tools for Visual Studio   2.6.5000.0
Bundler & Minifier   2.9.9
C# Tools   4.6.0-3.23259.8+c3cc1d0ceeab1a65da0217e403851a1e8a30086a
Common Azure Tools   1.10
Dotfuscator Community Edition   6.5.3+7f0b0a9d18
Extensibility Message Bus   1.4.21 (main@8f226a8)
File Icons   2.7
GhostDoc   22.2.22190.0
Microsoft Azure Hive Query Language Service   2.6.5000.0
Microsoft Azure Stream Analytics Language Service   2.6.5000.0
Microsoft Azure Tools for Visual Studio   2.9
Microsoft JVM Debugger   1.0
Mono Debugging for Visual Studio   17.6.41 (790a401)
NuGet Package Manager   6.6.0
Office Developer Tools for Visual Studio   17.6.33520.00
Razor (ASP.NET Core)   17.6.0.2327201+a6a61fdfa748eaa65aab53dab583276e26af4a3e
Sandcastle Help File Builder   SHFB
SQL Server Data Tools   17.6.13.0
SVG Viewer   1.0.16
Syntax Visualizer   1.0
ToolWindowHostedEditor   1.0
Tweaks 2022   1.1.143
TypeScript Tools   17.0.20329.2001
Visual Basic Tools   4.6.0-3.23259.8+c3cc1d0ceeab1a65da0217e403851a1e8a30086a
Visual F# Tools   17.6.0-beta.23174.5+0207bea1afae48d9351ac26fb51afc8260de0a97
Visual Studio IntelliCode   2.2
VisualStudio.DeviceLog   1.0
VisualStudio.Mac   1.0
Web Compiler   1.14.11
Workflow Manager Tools 1.0   1.0
Xamarin   17.6.0.251 (d17-6@318364c)
Xamarin Designer   17.6.6.0 (remotes/origin/d17-6@cb430751d1)
Xamarin Templates   17.6.32 (98c12a2)
Xamarin.Android SDK   13.2.0.6 (d17-5/a200af1)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: 6dd9def
    Java.Interop: xamarin/java.interop/d17-5@149d70fe
    SQLite: xamarin/sqlite/3.40.1@68c69d8
    Xamarin.Android Tools: xamarin/xamarin-android-tools/d17-5@9f02d77

Xamarin.iOS and Xamarin.Mac SDK   16.4.0.6 (97731c92c)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

**Comment by madskristensen** [comment]
Thanks for reporting this. A fix is on its way to the Marketplace right now
